apiVersion: v1
kind: Service
metadata:
 name: aggregatorservice
spec:
  type: LoadBalancer
  selector:
   app: sample-aggregator
  ports:
   - protocol: TCP
     port: 3000   # port on which cluster is runnin (access application from here)
     targetPort: 8080 # port given in deployment file on which application is running